### ISSUE TITLE
pretrained models can not be downloaded 

### ISSUE THREAD

**Issue by kaizhigaosu** [researchmm/soho#5]
"wget https://sohose.s3.ap-southeast-1.amazonaws.com/checkpoint/soho_res18_fp16_40-9441cdd3.pth"

I can not download this pth file even if i am using a  VPN. 

 It throw a "ERROR 403: Forbidden" error.

Can you fix it? thanks.

**Comment by ZhichengHuang** [comment]
We have fixed this issue, thanks.
